name: iac scan 
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
      - name: tfsec commenter
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          INPUT_GITHUB_TOKEN: ${{ secrets.APPROVERBOT_SECRET }}
          github_token: ${{ secrets.APPROVERBOT_SECRET }}
  Checkov:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,json # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: console,checkov.json # folder and name of results file
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform
          directory: './terraform/aws/'
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          #github_pat: ${{ secrets.APPROVERBOT_SECRET }}
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: checkov-report
          path: checkov.*
  KICS:
    runs-on: ubuntu-latest
    steps:
      - name: Mkdir myResults
        # make sure results dir is created
        run: mkdir -p myResults
      - name: Checkout
        uses: actions/checkout@v3  

      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
          path: './terraform/aws/'
          output_formats: json,csv
          output_path: myResults/
          ignore_on_exit: results
          token: ${{ secrets.IAC_TOKEN }}
          enable_comments: true
          enable_jobs_summary: true


      # Display the results in json format
      - name: display kics results
        run: |
          cat myResults/results.json
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: kics-report
          path: myResults/results.*
